repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis-test
    namespace: itsm-dev
    chart: bitnami/redis
    version: 20.2.1
    values:
      - replica:
          replicaCount: 1
